x-mysql:
  environment: &env_mysql
    MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-pass}
    MYSQL_DATABASE: ${MYSQL_DATABASE:-chat_app}
    MYSQL_USER: ${MYSQL_USER:-user}
    MYSQL_PASSWORD: ${MYSQL_PASSWORD:-pass}

x-db:
  environment: &env_db
    DB_CONNECTION: mysql
    DB_HOST: database
    DB_PORT: 3306
    DB_DATABASE: ${MYSQL_DATABASE:-chat_app}
    DB_USERNAME: ${MYSQL_USER:-user}
    DB_PASSWORD: ${MYSQL_PASSWORD:-pass}

x-other:
  environment: &other
    PHP_IDE_CONFIG: serverName=alert.localhost

services:
  database:
    container_name: database
    image: mysql
    environment:
      <<: [ *env_mysql ]
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql/
    networks:
      - chat_app

  php:
    container_name: php
    build:
      context: .
      dockerfile: php/Dockerfile
      target: php_base
    environment:
      <<: [
        *env_db,
        *other
      ]
    volumes:
      - ./chat-app:/var/www/chat-app
    networks:
      - chat_app

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    volumes:
      - ./nginx:/etc/nginx/conf.d/
      - ./chat-app/public:/var/www/chat-app/public
    depends_on:
      - php
      - database
    ports:
    - '8080:80'
    networks:
      - chat_app

volumes:
  mysql_data:

networks:
  chat_app:
